<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<!-- Third Party Libraries -->
		<PackageReference Include="ClosedXML" Version="0.105.0" />
		<PackageReference Include="CsvHelper" Version="33.1.0" />
		<PackageReference Include="EPPlus" Version="8.5.4" />
		<PackageReference Include="ExcelDataReader" Version="3.8.0" />
		<PackageReference Include="ExcelDataReader.DataSet" Version="3.8.0" />
		<PackageReference Include="itext7" Version="9.6.0" />
		<PackageReference Include="itext7.bouncy-castle-adapter" Version="9.6.0" />
		<PackageReference Include="MailKit" Version="4.16.0" />
		<PackageReference Include="MimeKit" Version="4.16.0" />
		<PackageReference Include="QuestPDF" Version="2026.5.0" />
		<!-- Entity Framework & Identity DB -->
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.8" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.8" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.8">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<!-- This single line brings in Blazor, Forms, Identity, and MVC automatically without warnings -->
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

</Project>